sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 111111
  s3:
    url: http://172.26.179.90:9000
    access-key: LIZpG1Fy19ZIGwjcx6bX
    secret-key: anIwLIJNJ6zTphopT56wqwrAM4bHxthnlDy0shu5
    bucketname: public 
    