sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 111111
  s3:
    url: http://172.26.179.90:9000
    access-key: LIZpG1Fy19ZIGwjcx6bX
    secret-key: anIwLIJNJ6zTphopT56wqwrAM4bHxthnlDy0shu5
    bucketname: public 
  redis:
    host: 172.26.179.90
    port: 6379
    password: 123456
  wechat:
    appid: wx3260654894227caf
    secret: 5b65e2669105df53b504e01b0c9edba7